name: Continuous Integration

on:
 push:
  branches:
   - main
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest
  env:
   docker_username: ${{secrets.DOCKERUSERNAME}}
   docker_password: ${{secrets.DOCKERPASSWORD}}
   DOCKER_IMAGE: karthikamn/flask-api-python-app
   SONARHOSTURL: ${{secrets. SONARHOSTURL}}
   SONARTOKEN: ${{secrets.SONARTOKEN}}
  steps:
   - name: Checkout
     uses: actions/checkout@v4.2.2
   - name: Official SonarQube Scan
     uses: SonarSource/sonarqube-scan-action@v5.1.0
     with:
      projectBaseDir: .
      args: >
       -Dsonar.projectKey=my-projectkey
       -Dsonar.host.url=${{env.SONARHOSTURL}}
       -Dsonar.login=${{env.SONARTOKEN}}
       -Dsonar.working.directory=./.scannerwork
   - name: SonarQube Quality Gate Check
     uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
     with:
        scanMetadataReportFile: .scannerwork/report-task.txt
      
     
   - name: Docker login
     uses: docker/login-action@v2
     with:
      username: ${{env.docker_username}}
      password: ${{env.docker_password}}
   - name: Build Docker image
     run: |
         docker build -t $DOCKER_IMAGE:${{ github.sha }} .
         docker tag $DOCKER_IMAGE:${{ github.sha }} $DOCKER_IMAGE:latest
 
