name: CI with Docker

on:
 push

env:
 DOCKER_USERNAME: ${{vars.DOCKER_NAME}}
 DOCKER_PASSWORD: ${{secrets.NEW_DOCKER_PASSWORD}}
 DOCKER_IMAGE: my-python-api-flask
jobs:
 build-using-docker:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout code 
     uses: actions/checkout@v4.2.2
   - name: Docker Login
     uses: docker/login-action@v3.4.0
     with:
      username: ${{env.DOCKER_USERNAME}}
      password: ${{env.DOCKER_PASSWORD}}
   - name: Docker Build
     run: |
      docker build -t $DOCKER_IMAGE:${{github.sha}}
      docker tag  $DOCKER_IMAGE:${{github.sha}} $DOCKER_IMAGE:latest
   - name: Push the Docker Image to Hub
     run: |
      docker push $DOCKER_IMAGE:${{ github.sha }}
      docker push $DOCKER_IMAGE:latest
 
